
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Jorge
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        jScrollPane3.setVisible(false);
        txt_Mensaje1.setVisible(false);
        lbl_CLexico.setVisible(false);
        lbl_CSemantico.setVisible(false);
        lbl_CSintaxis.setVisible(false);
        lbl_XLexico.setVisible(false);
        lbl_XSemantico.setVisible(false);
        lbl_XSintaxis.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Examinar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Codigo = new javax.swing.JTextArea();
        btn_Compilar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Mensaje = new javax.swing.JTextArea();
        btn_Nuevo = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        btn_Ejecutar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_CLexico = new javax.swing.JLabel();
        lbl_CSintaxis = new javax.swing.JLabel();
        lbl_CSemantico = new javax.swing.JLabel();
        lbl_XLexico = new javax.swing.JLabel();
        lbl_XSintaxis = new javax.swing.JLabel();
        lbl_XSemantico = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_Mensaje1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Examinar.setText("Examinar");
        btn_Examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExaminarActionPerformed(evt);
            }
        });

        txt_Codigo.setColumns(20);
        txt_Codigo.setRows(5);
        jScrollPane1.setViewportView(txt_Codigo);

        btn_Compilar.setText("Compilar");
        btn_Compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CompilarActionPerformed(evt);
            }
        });

        txt_Mensaje.setEditable(false);
        txt_Mensaje.setColumns(20);
        txt_Mensaje.setRows(5);
        jScrollPane2.setViewportView(txt_Mensaje);

        btn_Nuevo.setText("Nuevo");
        btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoActionPerformed(evt);
            }
        });

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_Ejecutar.setText("Ejecutar");
        btn_Ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EjecutarActionPerformed(evt);
            }
        });

        jLabel1.setText("Lexico:");

        jLabel2.setText("Sintaxis:");

        jLabel3.setText("Semantico:");

        lbl_CLexico.setForeground(new java.awt.Color(0, 102, 51));
        lbl_CLexico.setText("✔");

        lbl_CSintaxis.setForeground(new java.awt.Color(0, 102, 51));
        lbl_CSintaxis.setText("✔");

        lbl_CSemantico.setForeground(new java.awt.Color(0, 102, 51));
        lbl_CSemantico.setText("✔");

        lbl_XLexico.setForeground(new java.awt.Color(102, 0, 0));
        lbl_XLexico.setText("X");

        lbl_XSintaxis.setForeground(new java.awt.Color(102, 0, 0));
        lbl_XSintaxis.setText("X");

        lbl_XSemantico.setForeground(new java.awt.Color(102, 0, 0));
        lbl_XSemantico.setText("X");

        txt_Mensaje1.setEditable(false);
        txt_Mensaje1.setColumns(20);
        txt_Mensaje1.setRows(5);
        jScrollPane3.setViewportView(txt_Mensaje1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Examinar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Compilar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_XLexico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_CLexico)
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_XSintaxis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_CSintaxis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_XSemantico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_CSemantico)
                        .addGap(70, 70, 70)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Examinar)
                    .addComponent(btn_Nuevo)
                    .addComponent(btn_Guardar)
                    .addComponent(btn_Compilar)
                    .addComponent(btn_Ejecutar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(lbl_CLexico)
                        .addComponent(lbl_CSintaxis)
                        .addComponent(lbl_CSemantico)
                        .addComponent(lbl_XLexico)
                        .addComponent(lbl_XSintaxis)
                        .addComponent(lbl_XSemantico))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExaminarActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        // Mostrar el cuadro de diálogo de selección de archivo
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            try {
                BufferedReader br = new BufferedReader(new FileReader(archivoSeleccionado));
                String linea;
                txt_Codigo.setText(""); // Limpiar el JTextArea antes de agregar el nuevo contenido

                // Leer el contenido del archivo y agregarlo al JTextArea
                while ((linea = br.readLine()) != null) {
                    txt_Codigo.append(linea + "\n");
                }

                br.close();
            } catch (IOException ex) {
            }
        }

    }//GEN-LAST:event_btn_ExaminarActionPerformed

    private void btn_CompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CompilarActionPerformed
        // Obtiene el texto del JTextArea
        txt_Mensaje.setText("");
        lbl_CLexico.setVisible(false);
        lbl_CSemantico.setVisible(false);
        lbl_CSintaxis.setVisible(false);
        lbl_XLexico.setVisible(false);
        lbl_XSemantico.setVisible(false);
        lbl_XSintaxis.setVisible(false);
        String texto = txt_Codigo.getText();

        // Crea una instancia de la clase lexico y pasa el texto como argumento
        lexico miLexico = new lexico(texto);
        micompi compilador = new micompi(this);
        // Redirige la salida estándar (System.out) a un JTextArea
        PrintStream printStream = new PrintStream(new CustomOutputStream(txt_Mensaje1));
        System.setOut(printStream);

        compilador.ejecutarAnalisis(texto);
        
    }

    private void guardarTextoEnArchivo(File selectedFile, String texto) {
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter(selectedFile));
            writer.write(texto);
            writer.close();
            JOptionPane.showMessageDialog(null, "Contenido guardado en el archivo correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
        public void actualizarEstadoLexico(boolean error) {
        if (error==true) {
            lbl_XLexico.setVisible(true);
        } else {
            lbl_CLexico.setVisible(true);
        }
    }

    // Método para actualizar el estado sintáctico en la interfaz
    public void actualizarEstadoSintactico(boolean error) {
        if (error==true) {
            lbl_XSintaxis.setVisible(true);
        } else {
            lbl_CSintaxis.setVisible(true);
        }
    }

    // Método para actualizar el estado semántico en la interfaz
    public void actualizarEstadoSemantico(boolean error) {
        if (error==true) {
            lbl_XSemantico.setVisible(true);
        } else {
            lbl_CSemantico.setVisible(true);
        }
    }

// Clase CustomOutputStream para redirigir la salida estándar a un JTextArea
    class CustomOutputStream extends OutputStream {

        private JTextArea textArea;

        public CustomOutputStream(JTextArea textArea) {
            this.textArea = textArea;
        }

        @Override
        public void write(int b) throws IOException {
            // Escribe el byte como carácter en el JTextArea
            textArea.append(String.valueOf((char) b));
            // Mueve el cursor al final del JTextArea
            textArea.setCaretPosition(textArea.getDocument().getLength());
        }

    }//GEN-LAST:event_btn_CompilarActionPerformed

    private void btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoActionPerformed
        lbl_CLexico.setVisible(false);
        lbl_CSemantico.setVisible(false);
        lbl_CSintaxis.setVisible(false);
        lbl_XLexico.setVisible(false);
        lbl_XSemantico.setVisible(false);
        lbl_XSintaxis.setVisible(false);
        txt_Codigo.setText("");
        txt_Mensaje.setText("");
    }//GEN-LAST:event_btn_NuevoActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showSaveDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            guardarTextoEnArchivo(fileChooser.getSelectedFile(), txt_Codigo.getText());
        }
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_EjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EjecutarActionPerformed
        // TODO add your handling code here:
        lbl_CLexico.setVisible(false);
        lbl_CSemantico.setVisible(false);
        lbl_CSintaxis.setVisible(false);
        lbl_XLexico.setVisible(false);
        lbl_XSemantico.setVisible(false);
        lbl_XSintaxis.setVisible(false);
        txt_Mensaje.setText("");
        String texto = txt_Codigo.getText();
        // Crea una instancia de la clase lexico y pasa el texto como argumento
        lexico miLexico = new lexico(texto);
        // Redirige la salida estándar (System.out) a un JTextArea
        micompi compilador = new micompi(this);
        PrintStream printStream = new PrintStream(new CustomOutputStream(txt_Mensaje));
        System.setOut(printStream);

        compilador.ejecutarAnalisis(texto);
    }//GEN-LAST:event_btn_EjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Compilar;
    private javax.swing.JButton btn_Ejecutar;
    private javax.swing.JButton btn_Examinar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_CLexico;
    private javax.swing.JLabel lbl_CSemantico;
    private javax.swing.JLabel lbl_CSintaxis;
    private javax.swing.JLabel lbl_XLexico;
    private javax.swing.JLabel lbl_XSemantico;
    private javax.swing.JLabel lbl_XSintaxis;
    private javax.swing.JTextArea txt_Codigo;
    private javax.swing.JTextArea txt_Mensaje;
    private javax.swing.JTextArea txt_Mensaje1;
    // End of variables declaration//GEN-END:variables
}
